name: Test F2 on Linux

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    # Tests
    - name: Run testing
      run: go test ./cmd...
